version: '3'
services:
  db:
    container_name: first_prac
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./serv:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  server:
    container_name: first_prac
    build: ./serv
    restart: always
    volumes:
      - ./serv:/var/www/html
    ports:
    - "8080:80"
      